# Generated by Django 5.2.4 on 2025-07-11 17:41

import places.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_place_cover.jpg', null=True, upload_to=places.utils.place_image_upload_path),
        ),
    ]
