# Generated by Django 5.2.4 on 2025-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_profile_icon.jpg', null=True, upload_to='users/avatars/%Y/%m/%d/'),
        ),
    ]
